# _config.yml

url: "https://chphr.github.io"
baseurl: ""
title: "christoph-rieger.ca" # the name of your site, e.g. ACME Corp.
paginate: 1
paginate_path: "/page:num/"

plugins:
  - jekyll-postcss
  - jekyll-paginate

postcss:
  cache: false