# _config.yml

url: "https://chphr.github.io"
baseurl: ""
title: "christoph-rieger.ca" # the name of your site, e.g. ACME Corp.
paginate: 1
paginate_path: "/page:num/"
timezone: "America/Toronto"
markdown: kramdown

kramdown:
  input: GFM

plugins:
  - jekyll-postcss
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc

postcss:
  cache: false

# _config.yml
toc:
  item_class: text-slate-400 hover:text-lime-300 leading-7
