source 'https://rubygems.org'

gem 'jekyll'
gem 'webrick'

gem 'jekyll-postcss'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-toc'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-archives'
gem 'jekyll-environment-variables'
gem 'jekyll-sitemap'
gem 'jekyll-figure'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'rouge'